### PR TITLE
Add Hit Counter Badge in Dynamic Stats

### PR DESCRIPTION
**Pull request by kaustav202**
Feature to track hits on github a repo

### CODE REVIEW

**Comment by mrhrifat** [comment]
What does it mean. Can you explain it to me?

**Review by mrhrifat — COMMENTED** [review]
What does it mean. Can you explain it to me?

**Comment by kaustav202** [comment]
> What does it mean. Can you explain it to me?

It basically counts the total number of visitors on the user's github profile page ..so gets incremented with each hit to user's github profile url. The badge can be added in the README markdown to showcase the a user's acclaim and reach

**Review by mrhrifat — CHANGES_REQUESTED** [review]
No, I asked why there are 2 numbers like `8 / 9`. The number of visitors was not supposed to be just one, like `8`. 
image

One more thing please rearrange this badge in `Alphabetical` order & create a shortcut option in `Menu`

**Comment by kaustav202** [comment]
> No, I asked why there are 2 numbers like `8 / 9`. The number of visitors was not supposed to be just one, like `8`. image
> 
> One more thing please rearrange this badge in `Alphabetical` order & create a shortcut option in `Menu`

The first count is for that particular day and the second count is the total overall.
Sure ..updating the order.

**Review by mrhrifat — APPROVED** [review]
It's not rearranged properly. No matter I'll fix it. Thanks for your contribution.

**Pull request merged**
