### PR TITLE
added security tools: wireshark and burpsuite

### PR DESCRIPTION
**Pull request by JenilGajjar20**
I have added a category by the name **🧰 Security Tools**. I have added two security tools in this category: **Wireshark** and **Burpsuite**.

### CODE REVIEW

**Comment by alexandresanlim** [comment]
Could your split these changes? one to add new category and another to format document. Thank you.

**Comment by JenilGajjar20** [comment]
Do I need to make separate PRs for both changes?

**Comment by alexandresanlim** [comment]
yes pls.

**Comment by JenilGajjar20** [comment]
> yes pls.

PR-1: https://github.com/alexandresanlim/Badges4-README.md-Profile/pull/676
PR-2: https://github.com/alexandresanlim/Badges4-README.md-Profile/pull/677

**Pull request closed without merging**
