### PR TITLE
color change for figma & miro

### PR DESCRIPTION
**Pull request by topaja**
image
image

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
The badges  you've changed background color & badge color doesn't follow general way of rules. But there the `Mira` is looking fine compare to it's own Website but the `Figma` don't. 
Please change the `Figma` to it's previous style.

**Comment by topaja** [comment]
ok

**Comment by topaja** [comment]
I have changed `Figma` to its previous style now you can check

**Comment by topaja** [comment]
### also check this one as well 

-  `illustrator` 
-  `photoshop`
-  `lightroom`
-  `premiere pro`
-  `After effects` 
-  `Indesign`

image

**Comment by topaja** [comment]
- `snapchat`

image

**Review by mrhrifat — CHANGES_REQUESTED** [review]
The badge named `Miro` was looking good by compare with it official website although that was not the right way & that's why I was agreed to approve it. 
But now you have change many icons which is not following the right way & not looking so good. So please change those badges color as before as it was.

**Comment by topaja** [comment]
ok

**Comment by topaja** [comment]
created a new PR as per the above suggestion

**Pull request closed without merging**
