### PR TITLE
Oracle DB Added to Databases

### PR DESCRIPTION
**Pull request by CarlosLaurine**

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please rearrange your badge `Alphabetical` order.

**Comment by CarlosLaurine** [comment]
> Please rearrange your badge `Alphabetical` order.

All set👍

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Actually  it's not. Something is still missing
1. I think it will be only `Oracle` not `OracleDB`
2. You just render the viewer badge correctly, but the `URL` for use this badge isn't correct.

Please fix them & feel free to notify me if I'm wrong with any of my point.

**Comment by mrhrifat** [comment]
I respect your contribution to this repository but please don't make any request where you can't take a look to your request update or feedback from author & collaborator or someone else although you're active in GitHub. Thanks for your contributions.

**Review by mrhrifat — APPROVED** [review]

**Pull request merged**
