### PR TITLE
Gulp added in Frameworks slot `new-badge`

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Thanks for you nice contribution. But I think it's need a little change at `Language` section. 
- If `Groovy` is stand by it's own name than it should be after `F` & before `H`.
- But if we consider it with `Apache Groovy` than the `Apache` should be on badge.
- In [Groovy](https://groovy-lang.org/) website, it's domain are free from `Apache` but the logo has it.
- I would like to suggest make two badges. One will be with `Apache` & another one will be without `Apache` & make a commit of them in correct position. Thanks.
- If I'm wrong or if you have any feedback for mine. Please feel free to notify me.

**Comment by gurjeetsinghvirdee** [comment]
> Thanks for you nice contribution. But I think it's need a little change at `Language` section.
> 
> * If `Groovy` is stand by it's own name than it should be after `F` & before `H`.
> * But if we consider it with `Apache Groovy` than the `Apache` should be on badge.
> * In [Groovy](https://groovy-lang.org/) website, it's domain are free from `Apache` but the logo has it.
> * I would like to suggest make two badges. One will be with `Apache` & another one will be without `Apache` & make a commit of them in correct position. Thanks.
> * If I'm wrong or if you have any feedback for mine. Please feel free to notify me.

Thanks for your feedback!
I missed to write `Apache` in badge
But I have one issue:
* If I make with `Apache` then I get this same badge `Apache-Groovy` but If I remove the `Apache` from badge then their will be no icon will exist named `Groovy`

**Comment by mrhrifat** [comment]
Than, it will be good to keep only one badge named `Apache Groovy`. isn't it?

**Comment by gurjeetsinghvirdee** [comment]
> Than, it will be good to keep only one badge named `Apache Groovy`. isn't it?

Yeah it will be one badge!!
I fixed that name issue so now you can merge it.

**Review by mrhrifat — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
