### PR TITLE
Update qgis version

### PR DESCRIPTION
**Pull request by ambarja**

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
1. Please provide the source of `Qgis 3.24 Tisler` update release. I can't find it on their official website.
2. There is an error of `404: badge not found` at your change to second badge. Fix this also.

**Review by mrhrifat — CHANGES_REQUESTED** [review]
The problem has not been solved yet.
1. Please remove `?` from the 2nd URL in 773 line.

**Comment by ambarja** [comment]
Hi @mrhrifat , sorry but a the moment the webpage no update the version for the users windows, but on linux is totally diferent , here an screeshot, maybe the next week update the version in your page official

**Review by mrhrifat — APPROVED** [review]
Actually I wasn't sure about the `Qgis 3.24` update news because I didn't use neither Windows nor `Qgis`. That's why When I check it's official website I saw that, the latest update is probably `Qgis 3.22`.
This is reason I asked you for the source of update. Thanks for your contribution & nice response.

**Comment by ambarja** [comment]
@mrhrifat  > https://www.qgis.org/es/site/index.html
The new version now available.

**Comment by mrhrifat** [comment]
Thanks for your update information. Feel free to contribute.

**Pull request merged**
