### PR TITLE
Fix "Rollup" Spelling

### PR DESCRIPTION
**Pull request by cfuendesign**
Fixed spelling mistake so that the rollup badge can be used out of the box.

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Thanks for it. Please do one more thing, use same name at `rollup%20js` after `/badge/`

**Comment by cfuendesign** [comment]
> Please do one more thing, use same name at `rollup%20js` after `/badge/`

Sorry, I didn't understand what you mean. Do you want me to try add the dot `.` so that it says `rollup.js` ?

 <- Like this?

**Review by TAKYI-WONDER — APPROVED** [review]

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Remove the `.` & named as `rolup%20js` at both link.

**Comment by cfuendesign** [comment]
AH, I think I understand now! I'll add the changes.

**Review by mrhrifat — CHANGES_REQUESTED** [review]
You have change somthing which wasn't in need of change. The badge should be look like it 
image

**Comment by cfuendesign** [comment]
Done!

**Review by mrhrifat — APPROVED** [review]
Thanks for your contribution with patience.

**Pull request merged**
