### PR TITLE
Updated Pytorch Lightning name to Lightning

### PR DESCRIPTION
**Pull request by george-gca**

### CODE REVIEW

**Comment by george-gca** [comment]
Reference to name change: https://github.com/Lightning-AI/lightning#readme

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Remove `pytorch` from `logo=pytorch-lightning`.

**Comment by george-gca** [comment]
> Remove `pytorch` from `logo=pytorch-lightning`.

Actually, if I apply this change for the `logo` part the logo will not display, since the logo name have [not yet been updated](https://simpleicons.org/?q=lightning). I opened a [PR](https://github.com/simple-icons/simple-icons/pull/8415) for this.

**Review by mrhrifat — APPROVED** [review]
Ok.. Than if they change the logo name than update it later. 
Thanks for your contribution.

**Pull request merged**
