### PR TITLE
Updated new version QGIS

### PR DESCRIPTION
**Pull request by ambarja**
- https://www.qgis.org/es/site/

image

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please change the `version` at second URL also.

**Comment by ambarja** [comment]
> Please change the `version` at second URL also.

The second url is only the version n-n

**Review by mrhrifat — CHANGES_REQUESTED** [review]
I'm talking about the complexity on every badge that you've change only in render section `qgis-3.24_Tisler` but left the code for use as it was `qgis-3.22_Bia%C5%82owie%C5%BCa`

**Comment by mrhrifat** [comment]
I close this request due to no response of change request.

**Pull request closed without merging**
