### PR TITLE
add badge for zig lang

### PR DESCRIPTION
**Pull request by cfuendesign**
Added this badge for the low-level/systems programming language <a href="https://ziglang.org">Zig</a>

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please use logoColor `white` & zig `#F7A41D`.

**Comment by cfuendesign** [comment]
Changes applied!

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please keep the 2nd URL as same as 1st one.

**Comment by cfuendesign** [comment]
Fixed!

**Review by mrhrifat — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
