### PR TITLE
Created two badge's under the Food Category.

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
The badge's names are- McDonald's & Burger King.  
The alignment of the URL dash might be changed because of the long name of the badge.

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please use `%20` between `Buger King` empty space.

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Please change the 2nd link also as same as 1st one.

**Comment by Anmol-Baranwal** [comment]
I am sorry for the trouble since you had to request again for the same thing. I'm a little curious though, about why %20 was important to add since it was working just fine without it. Please explain!

**Comment by mrhrifat** [comment]
URLs cannot contain spaces. URL encoding normally replaces a space with a plus (+) sign or with `%20`

**Review by mrhrifat — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
