### PR TITLE
Create Collapsible section for improve UX

### PR DESCRIPTION
**Pull request by HorebParraud**
CleanShot 2021-09-15 at 17 40 01

---
CleanShot 2021-09-15 at 17 40 35

### CODE REVIEW

**Comment by alexandresanlim** [comment]
Hello, tks for your contribution, it's nice but has a small problem, when i want to get a badge, i enter with "ctrl+f" to find, how would it look in this case?

**Review by mrhrifat — COMMENTED** [review]
Ok. Best of luck @HorebParraud

**Review by HenrySoftwareStudio — APPROVED** [review]

**Comment by mrhrifat** [comment]
@HenrySoftwareStudio  Before make `changes, review & approve` any pull request, I think you need to understand the motive, changes & bugs of that request. Learn more about open source.

**Comment by mrhrifat** [comment]
@HenrySoftwareStudio Before make `changes, review & approve` any pull request, I think you need to understand the `motive, changes & bugs` of that request. Learn more about open source.

**Comment by mrhrifat** [comment]
@HenrySoftwareStudio  Before make `changes, review & approve` any pull request, make sure you have read, understand the `motive, changes & bugs` of code in any request. Thanks.

**Comment by mrhrifat** [comment]
Due to no progress & far from latest code structure. This request has been close.

**Pull request closed without merging**
