### PR TITLE
More specific color for PhpStorm

### PR DESCRIPTION
**Pull request by insign**
References:
https://www.jetbrains.com/phpstorm/
https://www.jetbrains.com/phpstorm/download
https://i.postimg.cc/Kc0S2hmx/Dominant-Colors-fefefe-000001-7256fe-af49f0-8d50f4-fa3192-cf31cc-6d44ba-c9b4da-453253-Dom.png

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
> References: https://www.jetbrains.com/phpstorm/ https://www.jetbrains.com/phpstorm/download https://i.postimg.cc/Kc0S2hmx/Dominant-Colors-fefefe-000001-7256fe-af49f0-8d50f4-fa3192-cf31cc-6d44ba-c9b4da-453253-Dom.png

Thank you for the reference but we didn't make badges. All badges provided by [Simple Icons](https://simpleicons.org/) you can create an issue in [Simple Icons](https://github.com/simple-icons/simple-icons/issues) to change the color schema

**Review by mrhrifat — COMMENTED** [review]
- This is the official website of [Jet Brains](https://www.jetbrains.com/phpstorm/). Where we get `PHP Strome` Software Product.

> https://www.jetbrains.com/phpstorm/

- As your given reference, in Official website the color of `PHP Strome` look like `Black`. And in badge the color code is `181717`. 

- That's why the badge look like this


- **Note:** For your kind information as @gurjeetsinghvirdee  says, I would like to correct the mistake that,  **We create badge with the help of logo & the logo is provide by `Simple Icons` & the badge schema is designed by project `Shield`**.

- If I'm wrong in any of my point, please feel free to notify me. Thanks for your nice contribution.

image

**Comment by mrhrifat** [comment]
Due to no response I close this issue.

**Comment by insign** [comment]
Well, the site uses a black icon, but in the desktop it's a mix of blue,
pink and purple.

But thanks.

**Pull request closed without merging**
