### PR TITLE
Activity Graph Updated

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
Issue No: #506 

GitHub Activity Graph URL Updated

### Before

before

### After

after

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
`Neutralionsjs` badge added in **Frameworks** Section!

**Review by mrhrifat — CHANGES_REQUESTED** [review]
You've update `Menu` section. There is no group for `Static/Dynamic` badges or others element. I think this isn't a good thing.
Please find an another soultion or revert it.

**Comment by gurjeetsinghvirdee** [comment]
> You've update `Menu` section. There is no group for `Static/Dynamic` badges or others element. I think this isn't a good thing. Please find an another soultion or revert it.

Let me fix this

**Comment by gurjeetsinghvirdee** [comment]
@mrhrifat done with changes

**Review by mrhrifat — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
