### PR TITLE
New stuff

### PR DESCRIPTION
**Pull request by LightDestory**
- Added new items
- New hardware section
- Uniform html tags
- Fixed preview -> link not equal

### CODE REVIEW

**Review by mrhrifat — CHANGES_REQUESTED** [review]
Thanks for your contribution. You did a lot of commits. There is some line to make changes-
01. `125` It will be better if you make them lowercase both of word
02. `263` Color code of Udemy isn't right
03. `273` Either use %20 or _ not both
04. `385` Logo color white
05. `397` Logo color white
06. `569` Logo  color white
07. `758` 1001
08. `857` Either use %20 or _ not both

Feel free to notify me if I'm wrong in any of my point or you can't understand.

**Comment by LightDestory** [comment]
> Thanks for your contribution. You did a lot of commits. There is some line to make changes-
> 
> 1. `125` It will be better if you make them lowercase both of word
> 2. `263` Color code of Udemy isn't right
> 3. `273` Either use %20 or _ not both
> 4. `385` Logo color white
> 5. `397` Logo color white
> 6. `569` Logo  color white
> 7. `758` 1001
> 8. `857` Either use %20 or _ not both
> 
> Feel free to notify me if I'm wrong in any of my point or you can't understand.

I fixed 125 but the others are not my own changes.

**Review by LightDestory — COMMENTED** [review]
fixes some lines

**Review by mrhrifat — CHANGES_REQUESTED** [review]
I'm sorry to say that, your method to generate badge is can be good in your system but the regex you have used it made a lot of mistakes in code to generate. It's hard for me to solve all of them.

**Review by LightDestory — COMMENTED** [review]
Rebased the PR to be more cleaner. Let me know if it is now good enought.

**Review by mrhrifat — COMMENTED** [review]
From 520-613 All of code aren't valid. Let me show you,  


That's not the only issue, your regex has made many breakdown to code. Please make another pull request & add/edit badges by custom.

**Pull request closed without merging**
